baseURL = 'https://lightszentip.github.io'
languageCode = 'en-GB'
title = ''
lastmod = true
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true
[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
  [services.googleAnalytics]
    ID = ""



[params]
author = "Lightszentip"
description = ""
github = "lightszentip"
email = ""
url = "https://github.com/lightszentip"
keywords = "blog"
rss = true
lastmod = true
userStatusEmoji = "😀"
favicon = "https://avatars.githubusercontent.com/u/3680505?v=4"
location = "Germany"
enableGitalk = false
enableSearch = true

[[params.links]]
title = "gnetos"
href = "https://gnetos.de"
icon = "https://avatars.githubusercontent.com/u/3680505?v=4"
[[params.links]]
title = "password-security"
href = "http://lightszentip.github.io/password-security/"


